apiVersion: v1
entries:
  airbyte:
  - apiVersion: v2
    appVersion: 0.35.12-alpha
    created: "2022-01-31T12:10:40.832753-05:00"
    dependencies:
    - name: common
      repository: https://charts.bitnami.com/bitnami
      tags:
      - bitnami-common
      version: 1.x.x
    - condition: postgresql.enabled
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 10.x.x
    - condition: minio.enabled
      name: minio
      repository: https://charts.bitnami.com/bitnami
      version: 7.x.x
    description: Helm chart to deploy airbyte
    digest: 597a83f5449132e50e49f6c761ce805fae954fabc81ad9a611ad2f92a6f15934
    name: airbyte
    type: application
    urls:
    - airbyte-0.3.0.tgz
    version: 0.3.0
generated: "2022-01-31T12:10:40.822666-05:00"
