apiVersion: v1
entries:
  airbyte:
  - apiVersion: v2
    appVersion: 0.39.18-alpha
    created: "2022-06-15T11:38:53.429911-04:00"
    dependencies:
    - name: common
      repository: https://charts.bitnami.com/bitnami
      tags:
      - bitnami-common
      version: 1.x.x
    - condition: postgresql.enabled
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 10.x.x
    - condition: logs.minio.enabled
      name: minio
      repository: https://charts.bitnami.com/bitnami
      version: 11.x.x
    description: Helm chart to deploy airbyte
    digest: 144075e759cbe852b56d423f47dd796823280db6498c2b795e902359f135bc17
    name: airbyte
    type: application
    urls:
    - airbyte-0.3.5.tgz
    version: 0.3.5
  - apiVersion: v2
    appVersion: 0.35.12-alpha
    created: "2022-06-15T11:38:53.417587-04:00"
    dependencies:
    - name: common
      repository: https://charts.bitnami.com/bitnami
      tags:
      - bitnami-common
      version: 1.x.x
    - condition: postgresql.enabled
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 10.x.x
    - condition: minio.enabled
      name: minio
      repository: https://charts.bitnami.com/bitnami
      version: 7.x.x
    description: Helm chart to deploy airbyte
    digest: 16437465373111dcef9e264032fe03301ca55de1b8280cf646cbd8c65cfbd1aa
    name: airbyte
    type: application
    urls:
    - airbyte-0.3.1.tgz
    version: 0.3.1
  - apiVersion: v2
    appVersion: 0.35.12-alpha
    created: "2022-06-15T11:38:53.407159-04:00"
    dependencies:
    - name: common
      repository: https://charts.bitnami.com/bitnami
      tags:
      - bitnami-common
      version: 1.x.x
    - condition: postgresql.enabled
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 10.x.x
    - condition: minio.enabled
      name: minio
      repository: https://charts.bitnami.com/bitnami
      version: 7.x.x
    description: Helm chart to deploy airbyte
    digest: 597a83f5449132e50e49f6c761ce805fae954fabc81ad9a611ad2f92a6f15934
    name: airbyte
    type: application
    urls:
    - airbyte-0.3.0.tgz
    version: 0.3.0
  common:
  - annotations:
      category: Infrastructure
    apiVersion: v2
    appVersion: 1.16.0
    created: "2022-06-15T11:38:53.431148-04:00"
    description: A Library Helm Chart for grouping common logic between bitnami charts. This chart is not deployable by itself.
    digest: 612ba0ee47eecb204499b7021508c8ebff38d8b50899be717de3e44e7aa78aec
    home: https://github.com/bitnami/charts/tree/master/bitnami/common
    icon: https://bitnami.com/downloads/logos/bitnami-mark.png
    keywords:
    - common
    - helper
    - template
    - function
    - bitnami
    maintainers:
    - name: Bitnami
      url: https://github.com/bitnami/charts
    name: common
    sources:
    - https://github.com/bitnami/charts
    - https://www.bitnami.com/
    type: library
    urls:
    - charts/common-1.16.0.tgz
    version: 1.16.0
  minio:
  - annotations:
      category: Infrastructure
    apiVersion: v2
    appVersion: 2022.6.11
    created: "2022-06-15T11:38:53.434111-04:00"
    dependencies:
    - name: common
      repository: https://charts.bitnami.com/bitnami
      tags:
      - bitnami-common
      version: 1.x.x
    description: MinIO(R) is an object storage server, compatible with Amazon S3 cloud storage service, mainly used for storing unstructured data (such as photos, videos, log files, etc.).
    digest: 4a4370b34b3380aaa96663429d3c6bd970838855589e4310e6bce968ee9cc1e7
    home: https://github.com/bitnami/charts/tree/master/bitnami/minio
    icon: https://bitnami.com/assets/stacks/minio/img/minio-stack-220x234.png
    keywords:
    - minio
    - storage
    - object-storage
    - s3
    - cluster
    maintainers:
    - name: Bitnami
      url: https://github.com/bitnami/charts
    name: minio
    sources:
    - https://github.com/bitnami/bitnami-docker-minio
    - https://min.io
    urls:
    - charts/minio-11.7.4.tgz
    version: 11.7.4
  postgresql:
  - annotations:
      category: Database
    apiVersion: v2
    appVersion: 11.14.0
    created: "2022-06-15T11:38:53.438108-04:00"
    dependencies:
    - name: common
      repository: https://charts.bitnami.com/bitnami
      version: 1.x.x
    description: Chart for PostgreSQL, an object-relational database management system (ORDBMS) with an emphasis on extensibility and on standards-compliance.
    digest: 6012be8e28cad57f87320c1b035b668c6d6d0325e384ce4732ec154e452dbca0
    home: https://github.com/bitnami/charts/tree/master/bitnami/postgresql
    icon: https://bitnami.com/assets/stacks/postgresql/img/postgresql-stack-220x234.png
    keywords:
    - postgresql
    - postgres
    - database
    - sql
    - replication
    - cluster
    maintainers:
    - email: containers@bitnami.com
      name: Bitnami
    - email: cedric@desaintmartin.fr
      name: desaintmartin
    name: postgresql
    sources:
    - https://github.com/bitnami/bitnami-docker-postgresql
    - https://www.postgresql.org/
    urls:
    - charts/postgresql-10.16.2.tgz
    version: 10.16.2
generated: "2022-06-15T11:38:53.395189-04:00"
